name: Health check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Login to app
        run: |
          curl -c cookies.txt -s -X POST https://camagru-tau.vercel.app/auth/signin \
            -d "username=${{ secrets.USERNAME }}&password=${{ secrets.PASSWORD }}"

      - name: Health check with session
        id: check
        run: |
          response=$(curl -b cookies.txt -s -o /tmp/response.txt -w "%{http_code}" https://camagru-tau.vercel.app/feed)
          body=$(cat /tmp/response.txt)
          echo "response_body=$body" >> $GITHUB_OUTPUT
          if [[ "$response" -ge 200 && "$response" -lt 300 ]]; then
            echo "✅ Authenticated health check passed"
          else
            echo "❌ Authenticated health check failed (HTTP $response)"
            exit 1

      - name: Notify Discord if failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: error
          details: |
            ❌ Authenticated health check failed
            Response body: ${{ steps.check.outputs.response_body }}
